from typing import Dict, List

keywords: Dict[str, List[str]] = {
    "math": [
        "math",
        "mathematica",
        "algebra",
        "geometry",
        "calculus",
        "trigonometry",
        "arithmetic",
        "statistics",
        "probability",
        "equation",
        "theorem",
        "proof",
        "function",
        "integral",
        "derivative",
        "matrix",
        "vector",
        "series",
        "sequence",
        "logarithm",
        "exponent",
        "ratio",
        "proportion",
        "mean",
        "median",
        "mode",
        "variance",
        "standard deviation",
        "normal distribution",
        "binomial distribution",
        "polynomial",
        "quadratic",
        "linear",
        "nonlinear",
        "differential equation",
        "graph",
        "plot",
        "coordinate",
        "axis",
        "slope",
        "intercept",
        "angle",
        "sin",
        "cos",
        "tan",
        "cot",
        "sec",
        "sine",
        "cosine",
        "tangent",
        "cotangent",
        "secant",
        "cosecant",
        "csc",
        "hypotenuse",
        "adjacent",
        "opposite",
        "prime number",
        "composite number",
        "factor",
        "multiple",
        "divisor",
        "fraction",
        "decimal",
        "percent",
        "permutation",
        "combination",
        "set",
        "subset",
        "union",
        "intersection",
        "probability distribution",
        "random variable",
        "symmetric",
        "asymmetric",
        "function",
        "domain",
        "range",
        "parabola",
        "hyperbola",
        "ellipse",
        "conic sections",
        "scalar",
        "dot product",
        "cross product",
        "eigenvalue",
        "eigenvector",
        "identity matrix",
        "determinant",
        "transpose",
        "inverse matrix",
        "system of equations",
        "linear transformation",
        "orthogonal",
        "projection",
        "angle bisector",
        "midpoint",
        "distance formula",
        "circumference",
        "area",
        "volume",
        "surface area",
        "unit circle",
        "radian",
        "degree",
        "sector",
        "arc",
        "chord",
        "geometric sequence",
        "arithmetic sequence",
        "infinity",
        "limit",
        "continuity",
        "convergence",
        "divergence",
        "power series",
        "taylor series",
        "maclaurin series",
        "partial fraction",
        "improper integral",
        "line integral",
        "surface integral",
        "triple integral",
    ],
    "математика": [
        "математика",
        "алгебра",
        "геометрія",
        "математичний аналіз",
        "тригонометрія",
        "арифметика",
        "статистика",
        "ймовірність",
        "рівняння",
        "теорема",
        "доведення",
        "функція",
        "інтеграл",
        "похідна",
        "матриця",
        "вектор",
        "ряд",
        "послідовність",
        "логарифм",
        "показник степеня",
        "відношення",
        "частка",
        "середнє",
        "медіана",
        "мода",
        "дисперсія",
        "середньоквадратичне відхилення",
        "нормальний розподіл",
        "біноміальний розподіл",
        "поліноміальний",
        "квадратичний",
        "лінійна",
        "нелінійна",
        "диференціальне рівняння",
        "графік",
        "діаграма",
        "координата",
        "вісь",
        "нахил",
        "перехват",
        "кут",
        "синус",
        "косинус",
        "тангенс",
        "котангенс",
        "секанс",
        "косеканс",
        "катет",
        "гіпотенуза",
        "прилеглий",
        "протилежний",
        "просте число",
        "складене число",
        "множник",
        "кратне",
        "дільник",
        "частка",
        "десятковий",
        "відсоток",
        "перестановка",
        "комбінація",
        "множина",
        "підмножина",
        "об'єднання",
        "перетин",
        "розподіл ймовірностей",
        "випадкова величина",
        "симетричний",
        "асиметричний",
        "функція",
        "область",
        "діапазон",
        "парабола",
        "гіпербола",
        "еліпс",
        "конічні перерізи",
        "скаляр",
        "точковий добуток",
        "перехресний добуток",
        "власне значення",
        "власний вектор",
        "матриця тотожності",
        "визначник",
        "транспонування",
        "обернена матриця",
        "система рівнянь",
        "лінійне перетворення",
        "ортогональ",
        "проекція",
        "бісектриса кута",
        "медіана",
        "формула відстані",
        "окружність",
        "площа",
        "об'єм",
        "площа поверхні",
        "одиниця кола",
        "радіан",
        "градус",
        "сектор",
        "дуга",
        "хорда",
        "геометрична послідовність",
        "арифметична послідовність",
        "нескінченність",
        "границя",
        "неперервність",
        "збіжність",
        "розбіжність",
        "степеневий ряд",
        "ряд Тейлора",
        "ряд Маклорена",
        "частковий дріб",
        "неправильний інтеграл",
        "лінійний інтеграл",
        "поверхневий інтеграл",
        "потрійний інтеграл",
    ],
    "physics": [
        "physics",
        "quantum mechanics",
        "relativity",
        "thermodynamics",
        "electromagnetism",
        "classical mechanics",
        "particle physics",
        "nuclear physics",
        "optics",
        "wave",
        "particle",
        "energy",
        "force",
        "motion",
        "velocity",
        "acceleration",
        "mass",
        "weight",
        "gravity",
        "magnetism",
        "electricity",
        "current",
        "voltage",
        "resistance",
        "circuit",
        "magnetic field",
        "electric field",
        "photon",
        "electron",
        "proton",
        "neutron",
        "atom",
        "molecule",
        "nucleus",
        "radioactivity",
        "fission",
        "fusion",
        "black hole",
        "big bang",
        "entropy",
        "enthalpy",
        "conduction",
        "convection",
        "radiation",
        "wave-particle duality",
        "superposition",
        "entanglement",
        "heisenberg uncertainty principle",
        "schrodinger's cat",
        "string theory",
        "standard model",
        "higgs boson",
        "dark matter",
        "dark energy",
        "gravitational waves",
        "relativistic effects",
        "time dilation",
        "length contraction",
        "inertia",
        "momentum",
        "angular momentum",
        "torque",
        "centripetal force",
        "centrifugal force",
        "kinetic energy",
        "potential energy",
        "work",
        "power",
        "conservation laws",
        "frame of reference",
        "wave function",
        "quantum state",
        "wave equation",
        "phase",
        "frequency",
        "wavelength",
        "amplitude",
        "interference",
        "diffraction",
        "polarization",
        "reflection",
        "refraction",
        "plasma",
        "boson",
        "fermion",
        "lepton",
        "quark",
        "gluons",
        "neutrino",
        "antimatter",
        "tachyon",
        "string",
        "brane",
        "multiverse",
        "spacetime",
        "singularity",
        "event horizon",
        "hawking radiation",
        "cosmology",
        "cosmic microwave background",
        "redshift",
        "blueshift",
        "doppler effect",
        "hubble's law",
        "expansion of the universe",
        "cosmic inflation",
        "dark flow",
        "supernova",
        "neutron star",
        "pulsar",
        "quasar",
        "gamma-ray burst",
        "solar wind",
        "magnetosphere",
        "aurora",
        "flux",
        "field lines",
        "ampere's law",
        "faraday's law",
        "gauss's law",
        "lorentz force",
        "coulomb's law",
        "kepler's laws",
        "newton's laws",
        "planck's constant",
        "speed of light",
        "universal constant",
        "atomic mass",
        "atomic number",
        "isotope",
        "half-life",
        "binding energy",
        "solid state physics",
        "semiconductor",
        "superconductor",
        "hall effect",
        "ferromagnetism",
    ],
    "фізика": [
        "фізика",
        "квантова механіка",
        "теорія відносності",
        "термодинаміка",
        "електромагнетизм",
        "класична механіка",
        "фізика елементарних частинок",
        "ядерна фізика",
        "оптика",
        "хвиля",
        "частинка",
        "енергія",
        "сила",
        "рух",
        "швидкість",
        "прискорення",
        "маса",
        "вага",
        "гравітація",
        "магнетизм",
        "електрика",
        "струм",
        "напруга",
        "опір",
        "контур",
        "магнітне поле",
        "електричне поле",
        "фотон",
        "електрон",
        "протон",
        "нейтрон",
        "атом",
        "молекула",
        "ядро",
        "радіоактивність",
        "поділ",
        "термоядерний синтез",
        "чорна діра",
        "великий вибух",
        "ентропія",
        "ентальпія",
        "провідність",
        "конвекція",
        "випромінювання",
        "хвильово-частинковий дуалізм",
        "суперпозиція",
        "заплутаність",
        "принцип невизначеності Гейзенберга",
        "кіт Шредінгера",
        "теорія струн",
        "стандартна модель",
        "бозон Хіггса",
        "темна матерія",
        "темна енергія",
        "гравітаційні хвилі",
        "релятивістські ефекти",
        "уповільнення часу",
        "скорочення довжини",
        "інерція",
        "імпульс",
        "кутовий момент",
        "крутний момент",
        "доцентрова сила",
        "відцентрова сила",
        "кінетична енергія",
        "потенційна енергія",
        "робота",
        "потужність",
        "закони збереження",
        "система відліку",
        "хвильова функція",
        "квантовий стан",
        "хвильове рівняння",
        "фаза",
        "частота",
        "довжина хвилі",
        "амплітуда",
        "інтерференція",
        "дифракція",
        "поляризація",
        "відбиття",
        "заломлення",
        "плазма",
        "бозон",
        "ферміон",
        "лептон",
        "кварк",
        "глюони",
        "нейтрино",
        "антиматерія",
        "тахіон",
        "струна",
        "бран",
        "мультивсесвіт",
        "простір-час",
        "сингулярність",
        "горизонт подій",
        "яструбине випромінювання",
        "космологія",
        "космічний мікрохвильовий фон",
        "червоне зміщення",
        "синє зміщення",
        "ефект Доплера",
        "закон Габбла",
        "розширення Всесвіту",
        "космічна інфляція",
        "темний потік",
        "наднова",
        "нейтронна зоря",
        "пульсар",
        "квазар",
        "гамма-спалах",
        "сонячний вітер",
        "магнітосфера",
        "полярне сяйво",
        "потік",
        "силові лінії",
        "закон Ампера",
        "закон Фарадея",
        "закон Гаусса",
        "сила Лоренца",
        "закон Кулона",
        "закони Кеплера",
        "закони Ньютона",
        "стала Планка",
        "швидкість світла",
        "універсальна стала",
        "атомна маса",
        "атомний номер",
        "ізотоп",
        "період напіврозпаду",
        "енергія зв'язку",
        "фізика твердого тіла",
        "напівпровідник",
        "надпровідник",
        "ефект Холла",
        "феромагнетизм",
    ],
    "history": [
        "history",
        "revolution",
        "war",
        "empire",
        "kingdom",
        "dynasty",
        "monarchy",
        "republic",
        "democracy",
        "constitution",
        "treaty",
        "colonization",
        "independence",
        "civilization",
        "ancient",
        "medieval",
        "modern",
        "industrialization",
        "renaissance",
        "enlightenment",
        "feudalism",
        "imperialism",
        "nationalism",
        "communism",
        "socialism",
        "capitalism",
        "fascism",
        "dictatorship",
        "cold war",
        "world war",
        "reformation",
        "crusades",
        "expedition",
        "exploration",
        "discovery",
        "trade",
        "silk road",
        "spice trade",
        "slavery",
        "abolition",
        "emancipation",
        "civil rights",
        "suffrage",
        "holocaust",
        "genocide",
        "revolutionary war",
        "civil war",
        "world war i",
        "world war ii",
        "great depression",
        "cold war",
        "cold war era",
        "space race",
        "arms race",
        "nuclear proliferation",
        "decolonization",
        "indian independence",
        "american revolution",
        "french revolution",
        "russian revolution",
        "chinese revolution",
        "cuban revolution",
        "vietnam war",
        "korean war",
        "gulf war",
        "iraq war",
        "afghanistan war",
        "middle ages",
        "renaissance period",
        "industrial revolution",
        "scientific revolution",
        "age of exploration",
        "age of enlightenment",
        "victorian era",
        "edwardian era",
        "progressive era",
        "roaring twenties",
        "great depression era",
        "post-war era",
        "cold war period",
        "digital age",
        "information age",
        "modern era",
        "ancient egypt",
        "ancient greece",
        "roman empire",
        "byzantine empire",
        "ottoman empire",
        "ming dynasty",
        "qing dynasty",
        "han dynasty",
        "gupta empire",
        "mauryan empire",
        "aztec empire",
        "inca empire",
        "maya civilization",
        "mesopotamia",
        "babylon",
        "persian empire",
        "carthage",
        "vikings",
        "mongol empire",
        "medieval europe",
        "feudal japan",
        "samurai",
        "shogunate",
        "mughal empire",
        "age of reason",
        "scientific enlightenment",
        "american civil rights movement",
        "women's suffrage",
        "the great migration",
        "civil disobedience",
        "nonviolent resistance",
        "apartheid",
        "mandela",
        "gandhi",
        "martin luther king jr.",
        "malcolm x",
        "che guevara",
        "mao zedong",
        "stalin",
        "hitler",
        "churchill",
        "fdr",
        "truman",
        "kennedy",
        "roosevelt",
        "cold war espionage",
        "berlin wall",
        "iron curtain",
        "nato",
        "warsaw pact",
        "marshall plan",
        "watergate",
        "cuban missile crisis",
        "yugoslav wars",
        "bosnian genocide",
        "rwanda genocide",
        "darfur conflict",
        "arab spring",
        "syrian civil war",
        "russo-ukrainian war",
        "brexit",
        "european union",
        "united nations",
        "nato",
        "world trade organization",
        "nafta",
        "trans-pacific partnership",
        "climate change",
        "global warming",
        "paris agreement",
    ],
    "історія": [
        "історія",
        "революція",
        "війна",
        "імперія",
        "королівство",
        "династія",
        "монархія",
        "республіка",
        "демократія",
        "конституція",
        "договір",
        "колонізація",
        "незалежність",
        "цивілізація",
        "античний",
        "середньовічний" "модерн",
        "індустріалізація",
        "ренесанс",
        "просвітництво",
        "феодалізм",
        "імперіалізм",
        "націоналізм",
        "комунізм",
        "соціалізм",
        "капіталізм",
        "фашизм",
        "диктатура",
        "холодна війна",
        "світова війна",
        "реформація",
        "нацизм",
        "хрестові походи",
        "експедиція",
        "дослідження",
        "відкриття",
        "торгівля",
        "шовковий шлях",
        "торгівля прянощами",
        "рабство",
        "скасування",
        "емансипація",
        "громадянські права",
        "виборче право",
        "голокост",
        "геноцид",
        "революційна війна",
        "громадянська війна",
        "перша світова війна",
        "друга світова війна",
        "велика депресія",
        "холодна війна",
        "епоха холодної війни",
        "космічна гонка",
        "гонка озброєнь",
        "розповсюдження ядерної зброї",
        "деколонізація",
        "незалежність Індії",
        "американська революція",
        "французька революція",
        "російська революція",
        "китайська революція",
        "кубинська революція",
        "в'єтнамська війна",
        "корейська війна",
        "війна в Перській затоці",
        "іракська війна",
        "війна в Афганістані",
        "середньовіччя",
        "епоха відродження",
        "промислова революція",
        "наукова революція",
        "епоха великих географічних відкриттів",
        "епоха просвітництва",
        "вікторіанська епоха",
        "едвардіанська епоха",
        "прогресивна епоха",
        "буремні двадцяті",
        "епоха великої депресії",
        "повоєнна епоха",
        "період холодної війни",
        "цифрова епоха",
        "інформаційна епоха",
        "сучасна епоха",
        "стародавній єгипет",
        "стародавня Греція",
        "римська імперія",
        "візантійська імперія",
        "османська імперія",
        "династія Мін",
        "династія Цин",
        "династія Хань",
        "імперія Гуптів",
        "імперія Маур'їв",
        "імперія ацтеків",
        "імперія інків",
        "цивілізація майя",
        "месопотамія",
        "вавилон",
        "перська імперія",
        "карфаген",
        "вікінги",
        "монгольська імперія",
        "середньовічна Європа",
        "феодальна Японія",
        "самураї",
        "сьогунат",
        "імперія Великих Моголів",
        "епоха розуму",
        "наукове просвітництво",
        "американський рух за громадянські права",
        "жіноче виборче право",
        "велике переселення народів",
        "громадянська непокора",
        "ненасильницький опір",
        "апартеїд",
        "мандела",
        "ганді",
        "мартін лютер король молодший",
        "малкольм ікс",
        "че гевара",
        "мао цзедун",
        "сталін",
        "гітлер",
        "черчилль",
        "рузвельт",
        "трумен",
        "кеннеді",
        "рузвельт",
        "шпигунство часів холодної війни",
        "берлінський мур",
        "залізна завіса",
        "нато",
        "варшавський пакт",
        "план Маршалла",
        "Вотергейт",
        "Карибська криза",
        "югославські війни",
        "боснійський геноцид",
        "геноцид в руанді",
        "дарфурський конфлікт",
        "арабська весна",
        "громадянська війна в сирії",
        "російсько-українська війна",
        "брекзит",
        "європейський союз",
        "об'єднані нації",
        "нато",
        "світова організація торгівлі",
        "нафта",
        "транстихоокеанське партнерство",
        "зміна клімату",
        "глобальне потепління",
        "паризька угода",
    ],
    "technology": [
        "artificial intelligence",
        "software",
        "hardware",
        "programming",
        "coding",
        "algorithm",
        "machine learning",
        "artificial intelligence",
        "ai",
        "neural networks",
        "deep learning",
        "data science",
        "big data",
        "cloud computing",
        "internet of things",
        "iot",
        "cybersecurity",
        "encryption",
        "blockchain",
        "cryptocurrency",
        "bitcoin",
        "ethereum",
        "smart contract",
        "virtual reality",
        "vr",
        "augmented reality",
        "ar",
        "robotics",
        "automation",
        "3d printing",
        "biotechnology",
        "genetic engineering",
        "nanotechnology",
        "quantum computing",
        "quantum technology",
        "5g",
        "wireless communication",
        "network",
        "database",
        "sql",
        "nosql",
        "web development",
        "frontend",
        "backend",
        "full stack",
        "html",
        "css",
        "javascript",
        "react",
        "angular",
        "vue",
        "node.js",
        "python",
        "java",
        "c++",
        "c#",
        "ruby",
        "swift",
        "kotlin",
        "mobile development",
        "ios",
        "android",
        "app development",
        "user interface",
        "ui",
        "user experience",
        "ux",
        "responsive design",
        "devops",
        "agile",
        "scrum",
        "kanban",
        "version control",
        "git",
        "github",
        "continuous integration",
        "ci",
        "continuous deployment",
        "cd",
        "containerization",
        "docker",
        "kubernetes",
        "microservices",
        "serverless",
        "cloud infrastructure",
        "aws",
        "azure",
        "google cloud",
        "gcp",
        "digital transformation",
        "edge computing",
        "fog computing",
        "smart home",
        "smart devices",
        "wearables",
        "fitness trackers",
        "health tech",
        "medtech",
        "fintech",
        "edtech",
        "proptech",
        "natural language processing",
        "nlp",
        "speech recognition",
        "chatbots",
        "virtual assistants",
        "augmented reality",
        "mixed reality",
        "extended reality",
        "er",
        "haptic technology",
        "3d modeling",
        "computer graphics",
        "game development",
        "simulation",
        "digital twins",
        "smart cities",
        "connected vehicles",
        "autonomous vehicles",
        "self-driving cars",
        "electric vehicles",
        "ev",
        "renewable energy",
        "solar power",
        "wind power",
        "hydroelectric power",
        "smart grid",
        "energy storage",
        "battery technology",
        "wearable tech",
        "smartwatch",
        "fitness tracker",
        "smart glasses",
        "e-learning",
        "online education",
        "moocs",
        "massive open online courses",
        "online collaboration",
        "telemedicine",
        "remote work",
        "digital workspace",
        "cryptography",
        "secure communications",
        "quantum encryption",
        "privacy",
        "data protection",
        "regtech",
        "insurtech",
        "agritech",
        "contech",
        "govtech",
        "martech",
        "hrtech",
        "legaltech",
        "real estate technology",
        "property management systems",
        "virtual real estate",
        "3d printing construction",
        "sustainable technology",
        "cleantech",
        "green technology",
        "environmental technology",
        "recycling technology",
        "waste management technology",
        "water purification technology",
        "air purification technology",
        "carbon capture",
        "carbon footprint reduction",
        "renewable materials",
        "biodegradable materials",
        "smart packaging",
        "advanced manufacturing",
        "industry 4.0",
        "internet of behaviors",
        "behavioral data",
        "personalization",
        "customer experience",
        "cx",
        "user journey",
        "touchpoints",
        "interaction design",
        "service design",
        "design thinking",
        "innovation management",
        "creative technology",
        "disruptive technology",
    ],
    "технології": [
        "штучний інтелект",
        "програмне забезпечення",
        "апаратне забезпечення",
        "програмування",
        "кодування",
        "алгоритм",
        "машинне навчання",
        "ai",
        "нейронні мережі",
        "глибоке навчання",
        "наука про дані",
        "великі дані",
        "хмарні обчислення",
        "інтернет речей",
        "iot",
        "кібербезпека",
        "шифрування",
        "блокчейн",
        "криптовалюта",
        "біткойн",
        "ethereum",
        "смарт-контракт",
        "віртуальна реальність",
        "vr",
        "доповнена реальність",
        "ar",
        "робототехніка",
        "автоматизація",
        "3d-друк",
        "біотехнології",
        "генна інженерія",
        "нанотехнології",
        "квантові обчислення",
        "квантові технології",
        "5g",
        "бездротовий зв'язок",
        "мережа",
        "база даних",
        "sql",
        "nosql",
        "веб-розробка",
        "фронтенд",
        "бекенд",
        "повний стек",
        "html",
        "css",
        "javascript",
        "react",
        "angular",
        "vue",
        "node.js",
        "python",
        "java",
        "c++",
        "c#",
        "ruby",
        "swift",
        "kotlin",
        "mobile development",
        "ios",
        "android",
        "розробка додатків",
        "user interface",
        "ui",
        "user experience",
        "ux",
        "адаптивний дизайн",
        "devops",
        "agile",
        "scrum",
        "канбан",
        "контроль версій",
        "git",
        "github",
        "безперервна інтеграція",
        "ci",
        "continuous deployment",
        "cd",
        "containerization",
        "docker",
        "kubernetes",
        "microservices",
        "serverless",
        "cloud infrastructure",
        "aws",
        "azure",
        "google cloud",
        "gcp",
        "digital transformation",
        "edge computing",
        "туманні обчислення",
        "розумний дім",
        "розумні пристрої",
        "wearables",
        "фітнес-трекери",
        "health tech",
        "medtech",
        "fintech",
        "edtech",
        "proptech",
        "обробка природної мови",
        "nlp",
        "розпізнавання мови",
        "чат-боти",
        "віртуальні асистенти",
        "доповнена реальність",
        "змішана реальність",
        "розширена реальність",
        "er",
        "тактильні технології",
        "3d моделювання",
        "комп'ютерна графіка",
        "розробка ігор",
        "симуляція",
        "цифрові двійники",
        "розумні міста",
        "підключені транспортні засоби",
        "автономні транспортні засоби",
        "самокеровані автомобілі",
        "електромобілі",
        "електромобілі",
        "відновлювана енергетика",
        "сонячна енергетика",
        "вітрова енергетика",
        "гідроенергетика",
        "розумні мережі",
        "накопичувачі енергії",
        "акумуляторні технології",
        "технології, що носяться",
        "розумні годинники",
        "фітнес-трекер",
        "розумні окуляри",
        "електронне навчання",
        "онлайн-освіта",
        "масові відкриті онлайн-курси",
        "онлайн-співпраця",
        "телемедицина",
        "віддалена робота",
        "цифровий робочий простір",
        "криптографія",
        "безпечні комунікації",
        "квантове шифрування",
        "конфіденційність",
        "захист даних",
        "regtech",
        "insurtech",
        "agritech",
        "contech",
        "govtech",
        "martech",
        "hrtech",
        "legaltech",
        "real estate technology",
        "системи управління нерухомістю",
        "віртуальна нерухомість",
        "3d-друк у будівництві",
        "сталі технології",
        "cleantech",
        "зелені технології",
        "екологічні технології",
        "технології переробки",
        "технології управління відходами",
        "технології очищення води",
        "технології очищення повітря",
        "уловлювання вуглецю",
        "зменшення вуглецевого сліду",
        "відновлювані матеріали",
        "біорозкладні матеріали",
        "розумне пакування",
        "передове виробництво",
        "індустрія 4.0",
        "інтернет поведінки",
        "поведінкові дані",
        "персоналізація",
        "клієнтський досвід",
        "шлях користувача",
        "точки дотику",
        "дизайн взаємодії",
        "сервіс-дизайн",
        "дизайн-мислення",
        "управління інноваціями",
        "креативні технології",
        "проривні технології",
    ],
    "riddles": [
        "riddle",
        "puzzle",
        "brain teaser",
        "what am I",
        "mystery",
        "conundrum",
        "enigma",
        "paradox",
        "trick question",
        "wordplay",
        "challenge",
        "logic puzzle",
        "mind bender",
        "cryptic",
        "riddle me this",
    ],
    "загадки": [
        "загадка",
        "головоломка",
        "дражнилка для мозку",
        "що я таке",
        "таємниця",
        "загадка",
        "енігма",
        "парадокс",
        "питання з підступом",
        "гра слів",
        "виклик",
        "логічна головоломка",
        "розумовий вигин",
        "загадковий",
        "загадай мені це",
    ],
}
